version: '3.8'
services:
  app:
    container_name: appDocker
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
  db:
    container_name: dbDocker
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 56248
      MYSQL_DATABASE: appDocker
      MYSQL_USER: thomaspalma
      MYSQL_PASSWORD: qwerty-thomas
    build:
      context: .
      dockerfile: ./sqlDocker/Dockerfile