version: '3.8'
services:
  app:
    container_name: appDocker
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: dbDocker
    ports:
      - "13306:3306"
    volumes:
      - db:
    environment:
      MYSQL_ROOT_PASSWORD: 56248
      MYSQL_DATABASE: appDocker
      # MYSQL_USER: thomaspalma
      # MYSQL_PASSWORD: qwerty-thomas
    # build:
      # context: .
      # dockerfile: ./sqlDocker/Dockerfile