FROM mariadb:10.4
#ADD /etc/mysql/mariadb.conf.d/50-server.cnf 50-server.cnf
#COPY /etc/mysql/mariadb.conf.d /usr/local/docker/mariadb
# ADD mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
COPY . /docker-entrypoint-initdb.d/